services:
  backend:
    build: ./backend
    container_name: django_backend
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DJANGO_SETTINGS_MODULE=SecretLink.settings
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - redis
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8000/api
    container_name: next_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
    volumes:
      - ./frontend:/app
      - /app/node_modules

  redis:
    image: redis:7-alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
