sonar.projectKey=apextosos-backend
sonar.projectName=Apextosos - Backend
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=venv/**,env/**,migrations/**,**/__pycache__/**,**/*.pyc

sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml

sonar.sourceEncoding=UTF-8
